sudo apt-get install -y graphicsmagick libgraphicsmagick1-dev;
wget http://pecl.php.net/get/gmagick-1.1.7RC3.tgz;
tar -xzf gmagick-1.1.7RC3.tgz;
cd gmagick-1.1.7RC3;
phpize;
./configure --with-gmagick=/usr/local;
make -j;
sudo make install;
echo "extension=gmagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
php --ri gmagick;
